post_cb({"bq_ids": {"n4140": {"so_30691144_30691144_0": {"length": 5, "quality": 0.7142857142857143, "section_id": 7193}}, "n3337": {"so_30691144_30691144_0": {"length": 5, "quality": 0.7142857142857143, "section_id": 3060}}, "n4659": {"so_30691144_30691144_0": {"length": 5, "quality": 0.7142857142857143, "section_id": 1304}}}, "30691144": {"ViewCount": "39", "Body": "<pre><code>#include &lt;iostream&gt;\nusing namespace std;\nclass A\n{\n    public:\n    void g() noexcept {}\n    void f() noexcept( noexcept( g() )) {};\n};\n\nA a;\nint main()\n{\n    cout&lt;&lt;noexcept(a.f())&lt;&lt;endl;\n    return 0;\n}\n</code></pre>\n<p>When I try to compile this program with gcc 5.1.1, I got an error - </p>\n<blockquote>\n<p id=\"so_30691144_30691144_0\">Error: cannot call member function without object \u2018void A::g()\u2019</p>\n<p id=\"so_30691144_30691144_1\">||      void f() noexcept( noexcept( g() )) {};</p>\n</blockquote>\n<p>However, in clang++3.6 this can be compiled and the output is <code>1</code></p>\n<p>Is there any way to resolve this problem?</p>\n", "Title": "noexcept : different behavior on clang++ and g++", "CreationDate": "2015-06-07T07:28:25.757", "LastActivityDate": "2015-06-07T07:28:25.757", "CommentCount": "2", "PostTypeId": "1", "ClosedDate": "2015-06-07T08:01:33.817", "Id": "30691144", "Score": "0", "OwnerUserId": "4140668", "Tags": "<c++><c++11><gcc><clang><noexcept>", "AnswerCount": "0"}});